version: '3.0'

services:
  rasa:
    image: rasa/rasa:latest-full
    ports:
      - 5005:5005
    volumes:
      - ./Rasa/:/app
    command:
      - run


  action_server:
    image: rasa/rasa-sdk:latest
    volumes:
      - ./Rasa/actions:/app/actions