version: '2'

services:


  # =============================== Mongo =================================
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    volumes: 
      - ./db/telegram_db:/data/db
    hostname: mongo
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: 'admin'
    #   MONGO_INITDB_ROOT_PASSWORD: '1234'
    expose:
     - "27017"


  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - 8081:8081
    # environment:
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: admin
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: "1234"

  # =============================== Coach =================================
  # All the models are trained by this coach.
  coach:
    build:
      context: .
      dockerfile: ./docker/coach.Dockerfile
    volumes:
      - ./bot/models/:/bot/models/
    command: sh -c "make train"


  # ================================= Bot =====================================
  # Generic Rasa bot, used to run console for example.
  bot:
    image: lappis/bot:boilerplate
    build:
      context: .
      dockerfile: ./docker/bot.Dockerfile
    restart: unless-stopped
    ports:
      - 5004:5004
    depends_on:
      - actions
      - mongo
      - mongo-express

  # ================================= Actions =================================
  # Rasa middleware used to connect with external APIs.
  actions:
    build:
      context: .
      dockerfile: ./docker/actions.Dockerfile
    ports:
      - 5055:5055
    volumes:
      - ./bot/actions:/bot/actions
    command: sh -c "make run-actions"

  # ============================ Telegram Bot =================================
  # Specific Rasa bot integrated with Telegram.
  bot_telegram:
      build:
        context: .
        dockerfile: ./docker/bot.Dockerfile
      env_file:
        - env/bot-telegram.env
      ports:
        - 5001:5001
      depends_on:
        - actions
        - mongo
        - mongo-express
      volumes:
        - ./bot:/bot
        
      command: sh -c "make telegram"

volumes:
  mongo_data:
  esdata:
    driver: local
