language: pt
pipeline: 
 - name: WhitespaceTokenizer
 - name: CRFEntityExtractor
 - name: EntitySynonymMapper
 - name: CountVectorsFeaturizer
 - name: EmbeddingIntentClassifier

policies: 
 - name: MappingPolicy
 - name: "KerasPolicy"
   featurizer:
   - name: FullDialogueTrackerFeaturizer
     state_featurizer:
       - name: BinarySingleStateFeaturizer
 - name: "MemoizationPolicy"
