language : "pt"
pipeline:
 - name: "WhitespaceTokenizer"
 - name: "CRFEntityExtractor"
 - name: "EntitySynonymMapper"
 - name: "CountVectorsFeaturizer"
 - name: "EmbeddingIntentClassifier"

policies:
 - name: MappingPolicy
 - name: KerasPolicy
 - name: FallbackPolicy
 - name: MemoizationPolicy
   
