# language : "pt"
# pipeline:
#     - name: "WhitespaceTokenizer"
#     - name: "CRFEntityExtractor"
#     - name: "EntitySynonymMapper"
#     - name: "CountVectorsFeaturizer"
#     - name: "EmbeddingIntentClassifier"

# policies:
#   - name: KerasPolicy
#     epochs: 10
#     batch_size: 10
#     featurizer:
#       - name: FullDialogueTrackerFeaturizer
#         state_featurizer:
#           - name: LabelTokenizerSingleStateFeaturizer
#   - name: FallbackPolicy
#     nlu_threshold: 0.6
#     core_threshold: 0.6
#   - name: MemoizationPolicy
#     max_history: 4

# --------------------------------------------------------------------------

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline: supervised_embeddings

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy